# Generated by Django 3.0.7 on 2020-08-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_raffle_start_date_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Raffle', verbose_name='raffle')),
            ],
            options={
                'verbose_name': 'notification subscription',
                'verbose_name_plural': 'notification subscriptions',
                'unique_together': {('raffle', 'token')},
            },
        ),
    ]
