# Generated by Django 3.0.7 on 2020-08-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_raffle_start_date_helper'),
        ('notifications', '0002_auto_20200804_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsubscription',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Raffle'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ONE_HOUR', 'ONE_HOUR'), ('ONE_MINUTE', 'ONE_MINUTE'), ('HAS_STARTED', 'HAS_STARTED'), ('HAS_ENDED', 'HAS_ENDED')], max_length=20)),
                ('notification_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationSubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
