# Generated by Django 3.0.7 on 2020-08-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200805_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
