# Generated by Django 3.0.7 on 2020-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
