# Generated by Django 3.0.7 on 2021-06-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('params', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('CREATED', 'created'), ('IN_QUEUE', 'in_queue'), ('IN_PROGRESS', 'in_progress'), ('COMPLETE', 'complete'), ('ERROR', 'error')], default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
