# Generated by Django 3.0.7 on 2020-07-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_texteditorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultstable',
            name='raffle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result_table', to='core.Raffle', verbose_name='raffle'),
        ),
    ]
