# Generated by Django 3.0.7 on 2020-07-02 18:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200702_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name="raffle's end date and time"),
        ),
        migrations.AlterField(
            model_name='texteditorimage',
            name='location',
            field=models.ImageField(upload_to='text_editor_images/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterUniqueTogether(
            name='raffleevent',
            unique_together={('raffle', 'event')},
        ),
    ]
