# Generated by Django 3.0.7 on 2020-07-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200702_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=255, verbose_name='event id'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='token',
            field=models.CharField(max_length=256, verbose_name='raffle token'),
        ),
        migrations.AlterField(
            model_name='raffleevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_raffles', to='core.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='raffleevent',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_events', to='core.Raffle', verbose_name='raffle'),
        ),
    ]
