# Generated by Django 3.0.7 on 2020-07-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200702_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='events',
            field=models.ManyToManyField(related_name='raffles', through='core.RaffleEvent', to='core.Event', verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='raffleevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_raffles', to='core.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='raffleevent',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_events', to='core.Raffle', verbose_name='raffle'),
        ),
    ]
