# Generated by Django 3.0.7 on 2020-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200713_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['raffle', 'order'], 'verbose_name': 'prize', 'verbose_name_plural': 'prizes'},
        ),
    ]
