# Generated by Django 3.0.7 on 2020-07-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200713_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockdata',
            old_name='nonce',
            new_name='gas_limit',
        ),
        migrations.RemoveField(
            model_name='blockdata',
            name='seed',
        ),
    ]
