# Generated by Django 3.0.7 on 2020-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200713_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='poap_id',
            field=models.BigIntegerField(verbose_name='poap id'),
        ),
    ]
