# Generated by Django 3.0.7 on 2020-07-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200713_1703'),
        ('core', '0011_auto_20200713_1223'),
    ]

    operations = [
    ]
