# Generated by Django 3.0.7 on 2020-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200715_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='signature',
            field=models.CharField(default='', max_length=255, verbose_name='signature'),
            preserve_default=False,
        ),
    ]
