# Generated by Django 3.0.7 on 2020-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_participant_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event_id',
            field=models.CharField(default='1', max_length=100, verbose_name='event id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='poap_id',
            field=models.CharField(max_length=100, verbose_name='poap id'),
        ),
    ]
