# Generated by Django 3.0.7 on 2020-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200720_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='message'),
        ),
    ]
