# Generated by Django 3.0.7 on 2020-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_participant_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
    ]
