# Generated by Django 3.0.7 on 2020-07-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200722_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultstableentry',
            options={'ordering': ['results_table', 'order'], 'verbose_name': 'results table entry', 'verbose_name_plural': 'results table entries'},
        ),
        migrations.AddField(
            model_name='participant',
            name='ens_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ens name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='poap_id',
            field=models.IntegerField(verbose_name='poap id'),
        ),
    ]
