# Generated by Django 3.0.7 on 2020-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200729_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='raffle_created_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
