# Generated by Django 3.0.7 on 2020-07-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_emailconfiguration_raffle_created_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='draw_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name="raffle's draw date and time"),
        ),
    ]
