# Generated by Django 3.0.7 on 2020-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blockdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
