# Generated by Django 3.0.7 on 2020-08-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200807_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='new_raffle_cco_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
