# Generated by Django 3.0.7 on 2020-08-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_emailconfiguration_new_raffle_cco_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfiguration',
            old_name='new_raffle_cco_email',
            new_name='new_raffle_bcc_email',
        ),
    ]
