# Generated by Django 3.0.7 on 2020-09-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200827_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='new_raffle_bcc_email',
            field=models.CharField(blank=True, help_text='BCC recipients separated by comma of new raffle email', max_length=255, null=True),
        ),
    ]
