# Generated by Django 3.0.7 on 2021-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200903_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='email_required',
            field=models.BooleanField(default=False, verbose_name='email required'),
        ),
    ]
