# Generated by Django 3.0.7 on 2021-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rafflelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
