# Generated by Hand on 2021-09-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210422_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockdata',
            old_name='gas_limit',
            new_name='gas_used',
        ),
        migrations.AlterField(
            model_name='blockdata',
            name='gas_used',
            field=models.BigIntegerField(verbose_name='gas used'),
        ),
    ]
